clear all;  close all;  clc;
addpath(genpath('G:\Util0'))
%% General Parameter Set============================================
    for idxsg = 1	                                                       % Save path name   set              
        File_00_path = '..\';                                
        File_00_Dash = '\'; 
        File_00_Line = '_'; 
        File_01_sav = 'sav'; 
        File_02_raw = 'raw'; 
        File_04_rec = 'rec'; 
        File_06_pro = 'pro'; 
        File_0a_sim = 'sim'; 
        File_0b_exp = 'exp'; 
        File_0c_bkg = 'bkg'; 

        File_10_WFMPSF        = '1WFMPSF'; 
        File_11_WFMPSF_SimSav = [File_00_path,File_10_WFMPSF,'_1',File_0a_sim,File_01_sav];mkdir(File_11_WFMPSF_SimSav);
        File_12_WFMPSF_ExpRaw = [File_00_path,File_10_WFMPSF,'_2',File_0b_exp,File_02_raw];mkdir(File_12_WFMPSF_ExpRaw);
        File_13_WFMPSF_BkgRaw = [File_00_path,File_10_WFMPSF,'_3',File_0c_bkg,File_02_raw];mkdir(File_13_WFMPSF_BkgRaw);
        File_14_WFMPSF_SimRec = [File_00_path,File_10_WFMPSF,'_4',File_0a_sim,File_04_rec];mkdir(File_14_WFMPSF_SimRec);
        File_15_WFMPSF_ExpRec = [File_00_path,File_10_WFMPSF,'_5',File_0b_exp,File_04_rec];mkdir(File_15_WFMPSF_ExpRec);
        File_16_WFMPSF_ExpPro = [File_00_path,File_10_WFMPSF,'_6',File_0b_exp,File_06_pro];
        
        File_20_WFMImg        = '2WFMImg'; 
        File_21_WFMImg_SimSav = [File_00_path,File_20_WFMImg,'_1',File_0a_sim,File_01_sav];mkdir(File_21_WFMImg_SimSav);
        File_22_WFMImg_ExpRaw = [File_00_path,File_20_WFMImg,'_2',File_0b_exp,File_02_raw];mkdir(File_22_WFMImg_ExpRaw);
        File_23_WFMImg_BkgRaw = [File_00_path,File_20_WFMImg,'_3',File_0c_bkg,File_02_raw];mkdir(File_23_WFMImg_BkgRaw);
        File_24_WFMImg_SimRec = [File_00_path,File_20_WFMImg,'_4',File_0a_sim,File_04_rec];mkdir(File_24_WFMImg_SimRec);
        File_25_WFMImg_ExpRec = [File_00_path,File_20_WFMImg,'_5',File_0b_exp,File_04_rec];mkdir(File_25_WFMImg_ExpRec);
        File_26_WFMImg_ExpPro = [File_00_path,File_20_WFMImg,'_6',File_0b_exp,File_06_pro];
        
        File_30_FLFPSF        = '3FLFPSF'; 
        File_31_FLFPSF_SimSav = [File_00_path,File_30_FLFPSF,'_1',File_0a_sim,File_01_sav];mkdir(File_31_FLFPSF_SimSav);
        File_32_FLFPSF_ExpRaw = [File_00_path,File_30_FLFPSF,'_2',File_0b_exp,File_02_raw];mkdir(File_32_FLFPSF_ExpRaw);
        File_33_FLFPSF_BkgRaw = [File_00_path,File_30_FLFPSF,'_3',File_0c_bkg,File_02_raw];mkdir(File_33_FLFPSF_BkgRaw);
        File_34_FLFPSF_SimRec = [File_00_path,File_30_FLFPSF,'_4',File_0a_sim,File_04_rec];
        File_35_FLFPSF_ExpRec = [File_00_path,File_30_FLFPSF,'_5',File_0b_exp,File_04_rec];
        File_36_FLFPSF_ExpPro = [File_00_path,File_30_FLFPSF,'_6',File_0b_exp,File_06_pro];
        
        File_40_FLFImg        = '4FLFImg'; 
        File_41_FLFImg_SimSav = [File_00_path,File_40_FLFImg,'_1',File_0a_sim,File_01_sav];mkdir(File_41_FLFImg_SimSav);
        File_42_FLFImg_ExpRaw = [File_00_path,File_40_FLFImg,'_2',File_0b_exp,File_02_raw];mkdir(File_42_FLFImg_ExpRaw);
        File_43_FLFImg_BkgRaw = [File_00_path,File_40_FLFImg,'_3',File_0c_bkg,File_02_raw];mkdir(File_43_FLFImg_BkgRaw);
        File_44_FLFImg_SimRec = [File_00_path,File_40_FLFImg,'_4',File_0a_sim,File_04_rec];
        File_45_FLFImg_ExpRec = [File_00_path,File_40_FLFImg,'_5',File_0b_exp,File_04_rec];
        File_46_FLFPSF_ExpPro = [File_00_path,File_40_FLFImg,'_6',File_0b_exp,File_06_pro];
        
        File_50_FLFVid        = '5FLFVid'; 
        File_51_FLFVid_SimSav = [File_00_path,File_50_FLFVid,'_1',File_0a_sim,File_01_sav];mkdir(File_51_FLFVid_SimSav);
        File_52_FLFVid_ExpRaw = [File_00_path,File_50_FLFVid,'_2',File_0b_exp,File_02_raw];mkdir(File_52_FLFVid_ExpRaw);
        File_53_FLFVid_BkgRaw = [File_00_path,File_50_FLFVid,'_3',File_0c_bkg,File_02_raw];mkdir(File_53_FLFVid_BkgRaw);
        File_54_FLFVid_SimRec = [File_00_path,File_50_FLFVid,'_4',File_0a_sim,File_04_rec];
        File_55_FLFVid_ExpRec = [File_00_path,File_50_FLFVid,'_5',File_0b_exp,File_04_rec];
        File_56_FLFVid_ExpPro = [File_00_path,File_50_FLFVid,'_6',File_0b_exp,File_06_pro];
        
        File_90_RayTracingsav = [File_00_path,'\','90_Ray_Tracingsave'];mkdir(File_90_RayTracingsav);
    end
    for idxsg = 1	                                                       % Save path name   set              
        Path_n415_Ground = '5_Ground';
        Path_n417_WFMImg = '7_WFMImg';
        Path_n418_FLFImg = '8_FLFImg';
        Path_n419_FLFrez = '9_FLFrez';
    end
    for idxsg = 1                                                          % Image  parameter set              
        Data_00_bit     = 16    ;                                          %get
        Data_00_maxval  = 2^Data_00_bit-1;
        Data_01_formIm  = '.tif';                                          %get
        Data_01_formVd  = '.avi';                                          %get
        Data_02_formDt  = '.mat';                                          %get
        Data_04_smoothn = 1;                                               %Get?Recons_00_NUMd
        Data_04_Oper_sm = fspecial('gaussian',[Data_04_smoothn Data_04_smoothn],0.6);
    end
%% System parameter set 100X_old_075
    for idxsg = 1                                                          % System parameter  set 40X_old_100 
        %objective lens
        Ma_01_obj = 100         ;          NA_01_obj = 1.45        ;       %get
        Ind01_obj = 1.515       ;                                          %get
        fn_01_obj = 1/2/NA_01_obj;
        Fl_01_tub = 200*1e-3;              Fl_01_obj = Fl_01_tub/Ma_01_obj;%get
        Dm_01_obj = Fl_01_obj*NA_01_obj*2;  
        %tube lens
        Dm_02_tub = 25 *1e-3;              Fl_02_tub = 200*1e-3;           %get
        fn_02_tub = Fl_02_tub/Dm_02_tub;        
        %entrance lens
        Dm_03_ent = 25*1e-3 ;              Fl_03_ent = 075*1e-3;           %get
        fn_03_ent = Fl_03_ent/Dm_03_ent;   
        %Microlens array
        Ind04_MLA = 1.515   ;              det_08MLA  = 1.00*1e-3;
        Dm_04_MLA = 25*1e-3 ;                
        Dm_04_mic = 600*1e-6;              Pi_04_MLA = 600*1e-6;
        fn_04_MLA = 28;                    Fl_04_MLA = Dm_04_mic*fn_04_MLA;%get
                                           Fl_04bMLA = Fl_04_MLA;
        %Camera
        Num05_cam = 2048;                  Pi_05_cam = 6.5*1e-6;           %get
        Dm_05_cam = Pi_05_cam*Num05_cam;                                   
        %Image lense
        Dm_07_img = 25*1e-3 ;              Fl_07_img = 75*1e-3;            %get
        fn_07_img = Fl_07_img/Dm_07_img;
        %Wavelengh and beadsize
        lambdaAir   =  680*1e-9;                                              % 
        lambdaLen   =  lambdaAir/Ind04_MLA;
        k0       =  2*pi*1        /lambdaAir;                                 % k
        kn       =  2*pi*Ind01_obj/lambdaAir;                                 % k
    end
    for idxsg = 1                                                          % Diviation para    set             
        del_01_oo = 0;                                                      %get
        del_02_ot = 0;                                                      %get
        del_03_te = 0;                                                      %get
        del_04_em = 0;                                                      %get
        del_05_mc = 0;                                                      %get
        dell05_mc  = del_05_mc/Fl_04_MLA;                                    
        del_06_ti = 0;                                                      %get
        del_07_ec = 0;                                                      %get
        %Distance
        dis_01_oo = del_01_oo + Fl_01_obj;                                  %get
        dis_02_ot = del_02_ot + Fl_01_obj + Fl_02_tub;                      %get
        dis_03_te = del_03_te + Fl_02_tub + Fl_03_ent;                      %get
        dis_04_em = del_04_em + Fl_03_ent;                                  %get
        dis_05_mc = del_05_mc + Fl_04_MLA;                                  %get
        dis_06_ti = del_06_ti + Fl_02_tub + Fl_07_img;                      %get
        dis_07_ec = del_07_ec + Fl_03_ent;                                  %get
    end
    for idxsg = 1                                                          % Object parameters set             
        Object_31_ZuFOV  = + 03.00*10^-6;                                  % Get
        Object_31_ZlFOV  = - 03.00*10^-6;                                  % Get
        Object_32_Z_stp  =   03.00*10^-6;                                  % Get
        
       [Object_31_ZmFOV,Object_33_ZuNum,Object_33_ZlNum,...
        Object_33_ZdNum,Object_34_Z_Ind,Object_35_ZCoor] = S01_Coord_create_ud(Object_31_ZuFOV,Object_31_ZlFOV,Object_32_Z_stp);
        Object_33hNumZd = Object_33_ZdNum;
    end
    for idxsg = 1                                                          % Simulation parameter set          
        Step_NIP_Finetune = 2*10^-8;                                       
        Step_Propergation = 1*10^-4;                                       
        
        Flag_WFMPSFOnly = 0;                                               % profile simulatn, Flag = 1
                                                                           % no profile simul, Flag = 0
        Flag_Simulation = 1;                                               % simulation only , Flag = 1
                                                                           % deconvolutionPSF, Flag = 0
        Flag_simPSFfine = 1;                                               % profile simulatn, Flag = 1
                                                                           % no profile simul, Flag = 0
                                                                           
                P291_NIP_Size_Ext = 003;                                     %  = 0
                P292_NIP_Size_Wav = 010;                                     %  = 0
                P293_NIP_Size_Num = 512;                                     % Parameter = 0
                
        Flag_Profilesim = 0;                                               % profile simulatn, piont_sim = 1
                                                                           % no profile simul, piont_sim = 0
        Flag_MLA_size_Odd = 1;                                               % set lenslets size odd      , Flag = 1
                                                                           % set lenslets size as normal, Flag = 0
        Flag_MLA_grid_Hex = 0;
        Flag_Lens_Tra_Cir = 0;
        Flag_Lens_Apt_Cir = 0;
        Flag_Lens_On_axis = 1;
        Flag_Lens_All_Use = 1;
        Flag_MLA_grid_Inv = 1;
        
        P490_MLA_Beam_Rat = 0;                                             
        P491_MLA_lens_Num = 3;
        P492_MLA_lens_Ext = 2;
        
        Para_Raytrace_step_xx = 0.05;                                      
        Para_Raytrace_Ray_num = 35;
        Para_draw_axis        = 0;
    end
%% System parameter set 100X_old_275
    for idxsg = 1                                                          % System parameter  set 40X_old_100 
       [Fl_01_obj,Dm_01_obj,fn_01_obj          ,...
        Fl_01_tub,Ma_01_obj,NA_01_obj,Ind01_obj,...
        Fl_02_tub,Dm_02_tub,fn_02_tub          ,...
        Fl_03_ent,Dm_03_ent,fn_03_ent          ,...
        Fl_04_MLA,Dm_04_MLA,fn_04_MLA,det_08MLA,...
        Fl_04bMLA,Dm_04_mic,Pi_04_MLA,Ind04_MLA,...
        Num05_cam,Dm_05_cam,Pi_05_cam          ,...
        Fl_07_img,Dm_07_img,fn_07_img          ,...
        lambdaAir,lambdaLen,k0       ,kn       ,...
        del_01_oo,del_02_ot,del_03_te,del_04_em,...
        del_05_mc,dell05_mc,del_06_ti,del_07_ec,...
        dis_01_oo,dis_02_ot,dis_03_te,dis_04_em,...
        dis_05_mc,dis_06_ti,dis_07_ec] = F11_FLFsys_para_100XOV2()
    end
    for idxsg = 1                                                          % Object parameters set             
        Object_31_ZuFOV  = + 05.00*10^-6;                                  % Get
        Object_31_ZlFOV  = - 05.00*10^-6;                                  % Get
        Object_32_Z_stp  =   00.10*10^-6;                                  % Get
        
       [Object_31_ZmFOV,Object_33_ZuNum,Object_33_ZlNum,...
        Object_33_ZdNum,Object_34_Z_Ind,Object_35_ZCoor] = S01_Coord_create_ud(Object_31_ZuFOV,Object_31_ZlFOV,Object_32_Z_stp);
    end
    for idxsg = 1                                                          % Simulation parameter set          
        Step_NIP_Finetune = 2*10^-8;                                       
        Step_Propergation = 1*10^-4;                                       
        
        Flag_WFMPSFOnly = 1;                                               % profile simulatn, piont_sim = 1
                                                                           % no profile simul, piont_sim = 0
        Flag_Simulation = 1;                                               % simulation only , piont_sim = 1
                                                                           % deconvolutionPSF, piont_sim = 0
        Flag_simPSFfine = 1;                                               % profile simulatn, piont_sim = 1
                                                                           % no profile simul, piont_sim = 0
                P291_NIP_Size_Ext = 3 ;
                P292_NIP_Size_Wav = 10;
                P293_NIP_Size_Num = 1851;
        Flag_Profilesim = 0;                                               % profile simulatn, piont_sim = 1
                                                                           % no profile simul, piont_sim = 0
        Flag_MLA_size_Odd = 1;                                               % set lenslets size odd      , Flag = 1
                                                                           % set lenslets size as normal, Flag = 0
        Flag_MLA_grid_Hex = 1;
        Flag_Lens_Tra_Cir = 0;
        Flag_Lens_Apt_Cir = 0;
        Flag_Lens_On_axis = 0;
        Flag_Lens_All_Use = 1;
        Flag_MLA_grid_Inv = 1;
                                     
        P490_MLA_Beam_Rat = 0;                                             
        P491_MLA_lens_Num = 3;
        P492_MLA_lens_Ext = 2;
        
        Para_Raytrace_step_xx = 0.05;                                      
        Para_Raytrace_Ray_num = 35;
        Para_draw_axis        = 0;
    end
%% System parameter set 016X_new_300/200
    for idxsg = 1                                                          % System parameter  set 016X_new_300/200 
       [Fl_01_obj,Dm_01_obj,fn_01_obj          ,...
        Fl_01_tub,Ma_01_obj,NA_01_obj,Ind01_obj,...
        Fl_02_tub,Dm_02_tub,fn_02_tub          ,...
        Fl_03_ent,Dm_03_ent,fn_03_ent          ,...
        Fl_04_MLA,Dm_04_MLA,fn_04_MLA,det_08MLA,...
        Fl_04bMLA,Dm_04_mic,Pi_04_MLA,Ind04_MLA,...
        Num05_cam,Dm_05_cam,Pi_05_cam          ,...
        Fl_07_img,Dm_07_img,fn_07_img          ,...
        lambdaAir,lambdaLen,k0       ,kn       ,...
        del_01_oo,del_02_ot,del_03_te,del_04_em,...
        del_05_mc,dell05_mc,del_06_ti,del_07_ec,...
        dis_01_oo,dis_02_ot,dis_03_te,dis_04_em,...
        dis_05_mc,dis_06_ti,dis_07_ec] = F13_FLFsys_para_016XWV2_680nm();
        
                                                                           % Simulation parameters set
	   [Step_NIP_Finetune,Step_Propergation,...
        Flag_WFMPSFOnly  ,Flag_Simulation  ,...
        Flag_simPSFfine  ,Flag_Profilesim  ,...
        P291_NIP_Size_Ext,P292_NIP_Size_Wav,P293_NIP_Size_Num,...
        P490_MLA_Beam_Rat,P491_MLA_lens_Num,...
        P492_MLA_lens_Ext,Flag_MLA_size_Odd,...
        Flag_MLA_grid_Hex,Flag_MLA_grid_Inv,...
        Flag_Lens_On_axis,Flag_Lens_All_Use,...
        Flag_Lens_Tra_Cir,Flag_Lens_Apt_Cir,...
        Flag_Aperture ] = F13_FLFsys_para_016XWV2_Sim();
    end
%% System Charaterization==================================================
    for idxsg = 1                                                          % Object parameters set             
        Object_31_ZuFOV  = + 200.000*10^-6;                                % Get
        Object_31_ZlFOV  = - 200.000*10^-6;                                % Get
        Object_32_Z_stp  =   000.400*10^-6;                                % Get
        
       [Object_31_ZmFOV,Object_33_ZuNum,Object_33_ZlNum,...
        Object_33_ZdNum,Object_34_Z_Ind,Object_35_ZCoor] = S01_Coord_create_ud(...
        Object_31_ZuFOV,Object_31_ZlFOV,Object_32_Z_stp);
    end
    for idxsg = 1                                                          % Ray tracing figure set and draw   
        Para_Raytrace_step_xx = 0.05;
        Para_Raytrace_Ray_num = 35;
        Para_draw_axis        = 0;
        
        Ini_coorr = 0.0;
        Ini_coorz = 0.5;
        F21_ray_tracing_CPU_20191221(dis_01_oo ,Fl_01_obj,Dm_01_obj,...
                                     dis_02_ot ,Fl_02_tub,Dm_02_tub,...
                                     dis_03_te ,Fl_03_ent,Dm_03_ent,...
                                     dis_04_em ,Fl_04_MLA,Dm_04_mic,...
                                     dis_05_mc ,Pi_04_MLA,Dm_04_MLA,...
                                     Ma_01_obj,NA_01_obj,Pi_05_cam,...
                                     Para_Raytrace_step_xx,Para_Raytrace_Ray_num,Ini_coorr,...
                                     Flag_Lens_On_axis    ,Para_draw_axis       ,Ini_coorz,...
                                     File_90_RayTracingsav,Data_01_formIm)
    end
    for idxta = 1                                                          % Theoretical predicted Character   
        %FLFM system AND FLFM system-imaging
       [Ma_06_Mic,Ma_06_FLF,fn_06_FLF                  ,...
        fn_06_sub,Ma_07_img                            ,...
        Theory_21_BakRd,Theory_22_NatRd                ,...
        Theory_23_FouRd,Theory_31_RatEl,Theory_31_NumEl,...
        Theory_41_ResNL,Theory_41_ResNA                ,...
        Theory_51_FWHML,Theory_52_FWHMA                ,...
        Theory_61_ResR0,Theory_62_ResZ0,Theory_63_ResZE,...
        Theory_71_FOVR0                                ,...
        Theory_72_DOFZ0,Theory_73_FOVZu,Theory_74_FOVZl,...
        Theory_32_NumEl,Theory_73_FOV_R,Theory_74_DOF_Z,...
        Theory_66_Res_R,Theory_67_Res_Z,Theory_68_ResZR] =  ...
        F30_FLFsys_Characters(Fl_01_obj,NA_01_obj,Ma_01_obj,...
                              Fl_01_tub,Fl_02_tub          ,...
                              Fl_03_ent,Fl_07_img          ,...
                              Fl_04_MLA,Dm_04_mic,Pi_04_MLA,...
                              fn_01_obj,fn_04_MLA,lambdaAir,...
                              del_05_mc,del_03_te,del_04_em,...
                              Object_34_Z_Ind);
        
       [Path_s010_objlam,Path_s020_FouLFM,Path_s040_zrange] = ...
        F31_FLFsys_para_Lable(Ma_01_obj,NA_01_obj,lambdaAir  ,...
                              Fl_02_tub,Fl_03_ent            ,...
                              Dm_04_mic,Pi_04_MLA,fn_04_MLA  ,...
                              Object_31_ZlFOV,Object_31_ZuFOV,Object_32_Z_stp);
    end
close all
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Object parameters set test
    for idxsg = 1                                                          % Object parameters set test        
        Object_31_ZuFOV  = + 210.00*10^-6;                                  % Get
        Object_31_ZlFOV  = - 210.00*10^-6;                                  % Get
        Object_32_Z_stp  =   420.00*10^-6;                                  % Get
        
       [Object_31_ZmFOV,Object_33_ZuNum,Object_33_ZlNum,...
        Object_33_ZdNum,Object_34_Z_Ind,Object_35_ZCoor] = S01_Coord_create_ud(...
        Object_31_ZuFOV,Object_31_ZlFOV,Object_32_Z_stp);
        Flag_Profilesim   = 0;                                               % profile simulatn, piont_sim = 1
        P492_MLA_lens_Ext = 2;
        P293_NIP_Size_Num = 1851;
    end
    for idxsg = 1                                                          % Ray tracing figure set and draw   
        Para_Raytrace_step_xx = 0.05;
        Para_Raytrace_Ray_num = 35;
        Para_draw_axis        = 0;
        
        Ini_coorr = 0.0;
        Ini_coorz = 0.5;
        F21_ray_tracing_CPU_20191221(dis_01_oo ,Fl_01_obj,Dm_01_obj,...
                                     dis_02_ot ,Fl_02_tub,Dm_02_tub,...
                                     dis_03_te ,Fl_03_ent,Dm_03_ent,...
                                     dis_04_em ,Fl_04_MLA,Dm_04_mic,...
                                     dis_05_mc ,Pi_04_MLA,Dm_04_MLA,...
                                     Ma_01_obj,NA_01_obj,Pi_05_cam,...
                                     Para_Raytrace_step_xx,Para_Raytrace_Ray_num,Ini_coorr,...
                                     Flag_Lens_On_axis    ,Para_draw_axis       ,Ini_coorz,...
                                     File_90_RayTracingsav,Data_01_formIm)
    end
    for idxta = 1                                                          % Theoretical predicted Character   
        %FLFM system AND FLFM system-imaging
       [Ma_06_Mic,Ma_06_FLF,fn_06_FLF                  ,...
        fn_06_sub,Ma_07_img                            ,...
        Theory_21_BakRd,Theory_22_NatRd                ,...
        Theory_23_FouRd,Theory_31_RatEl,Theory_31_NumEl,...
        Theory_41_ResNL,Theory_41_ResNA                ,...
        Theory_51_FWHML,Theory_52_FWHMA                ,...
        Theory_61_ResR0,Theory_62_ResZ0,Theory_63_ResZE,...
        Theory_71_FOVR0                                ,...
        Theory_72_DOFZ0,Theory_73_FOVZu,Theory_74_FOVZl,...
        Theory_32_NumEl,Theory_73_FOV_R,Theory_74_DOF_Z,...
        Theory_66_Res_R,Theory_67_Res_Z,Theory_68_ResZR] =  ...
        F30_FLFsys_Characters(Fl_01_obj,NA_01_obj,Ma_01_obj,...
                              Fl_01_tub,Fl_02_tub          ,...
                              Fl_03_ent,Fl_07_img          ,...
                              Fl_04_MLA,Dm_04_mic,Pi_04_MLA,...
                              fn_01_obj,fn_04_MLA,lambdaAir,...
                              del_05_mc,del_03_te,del_04_em,...
                              Object_34_Z_Ind);
        
       [Path_s010_objlam,Path_s020_FouLFM,Path_s040_zrange] = ...
        F31_FLFsys_para_Lable(Ma_01_obj,NA_01_obj,lambdaAir  ,...
                              Fl_02_tub,Fl_03_ent            ,...
                              Dm_04_mic,Pi_04_MLA,fn_04_MLA  ,...
                              Object_31_ZlFOV,Object_31_ZuFOV,Object_32_Z_stp);
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    for idxsg = 1                                                          % Sampling parameter set            
        NIP_SegSZ = 600;
        Data_05_Refine = 2;
        Data_05_DownRT = 1;                                                % Downsampling ratio
                                                                           % Mic & MLA & FLP characterization  
       [Data_06_CCD_DN   ,Data_06_CCD_RF   ,...
        P27_NIP_RefAr_Odd,P27_NIP_RefAr_Eve,...
        P27_WFM_RefAd_Odd,P27_WFM_RefAd_Eve,...
        P35_Len_NumPd_DN ,P37_Len_NumPd_RF ,P37_Len_NumAd_RF,...
        P47_Fou_NumAd_RF ,P47_MLA_NumAdSim ,P47_MLA_NumAd_RF,...
        Path_s031Lsample ,Path_s033Lsample                  ]...
      = F32_FLFsys_SampleL(                                                     ...
        Ma_06_Mic, NA_01_obj, Pi_04_MLA, Dm_04_mic, Pi_05_cam, Num05_cam       ,...
        Data_05_DownRT   ,Data_05_Refine   ,Object_31_ZmFOV  ,                  ...
        Theory_22_NatRd  ,Theory_23_FouRd  ,Theory_31_NumEl  ,Theory_41_ResNL  ,...
        P291_NIP_Size_Ext,P292_NIP_Size_Wav,P293_NIP_Size_Num,P492_MLA_lens_Ext,...
        Flag_Simulation  ,Flag_WFMPSFOnly  ,Flag_simPSFfine  ,P491_MLA_lens_Num,Flag_MLA_size_Odd)
                                                                           % Mic & MLA & FLP characterization  
        disp(['Size of PSF   = ' num2str(P27_NIP_RefAr_Odd) 'X' num2str(P27_NIP_RefAr_Odd) '' ]);
        disp(['Size of IMAGE = ' num2str(P47_MLA_NumAdSim ) 'X' num2str(P47_MLA_NumAdSim ) '' ]);
        disp(['Numb of layers= ' num2str(Object_33_ZdNum)                                  '' ]);
    end
    for idxta = 1                                                          % MLA pattern generated             
        if(Flag_MLA_grid_Hex==1)
            P41_Fou_MLATra = I26_MLA_Modulation_HEX_Aperture_Num(                       ... 
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF  ,...
                                     P37_Len_NumPd_RF,P37_Len_NumPd_RF,P37_Len_NumAd_RF,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,1.93            ,...
                                     Flag_Lens_Tra_Cir ,Flag_Lens_On_axis ,0,...
                                     Flag_Lens_All_Use ,Flag_MLA_grid_Inv);
            P42_Fou_MLAApt = I26_MLA_Modulation_HEX_Aperture_Num(                       ...
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF  ,...
                                     P37_Len_NumPd_RF,P37_Len_NumAd_RF,P37_Len_NumAd_RF,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,1.93            ,...
                                     Flag_Lens_Apt_Cir ,Flag_Lens_On_axis ,1               ,...
                                     Flag_Lens_All_Use ,Flag_MLA_grid_Inv);
        else
            P41_Fou_MLATra = I25_MLA_Modulation_SQU_Aperture_Num(                       ...  
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF  ,...
                                     P37_Len_NumPd_RF,P37_Len_NumPd_RF,P37_Len_NumAd_RF,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,P490_MLA_Beam_Rat ,...
                                     Flag_Lens_Tra_Cir ,Flag_Lens_On_axis ,0               ,...
                                     Flag_Lens_All_Use);
            P42_Fou_MLAApt = I25_MLA_Modulation_SQU_Aperture_Num(                        ...
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF   ,...
                                     P37_Len_NumPd_RF,P37_Len_NumAd_RF,P37_Len_NumAd_RF ,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,P490_MLA_Beam_Rat,...
                                     Flag_Lens_Apt_Cir ,Flag_Lens_On_axis ,1            ,...
                                     Flag_Lens_All_Use);
        end
    end
    for idxta = 1                                                          % Save path name generate           
        Path_s000neotime = char(datetime('now','TimeZone','local','Format','yyMMdd_HHmm'));
        Path_s11b_update = [File_11_WFMPSF_SimSav,Path_s000neotime];   mkdir(Path_s11b_update)
        Path_s11c_unifor = [Path_s11b_update,'\',...
                     'WFM_',Path_s010_objlam, Path_s040_zrange, Path_s031Lsample];
        Path_s31b_update = [File_31_FLFPSF_SimSav,Path_s000neotime];   mkdir(Path_s31b_update)
        Path_s31c_unifor = [Path_s31b_update,'\',...
                     'FLF_',Path_s020_FouLFM, Path_s040_zrange, Path_s033Lsample];
    end
    for idxta = 1                                                          % Wave propogation                  
        close all;      clc;        disp('Start Calculating CSF...');
        % Wave propogation                                                 
        Flag_Startpoint = 1
        Flag_Finalpoint = 3
                                  
        H46_calcPSF_WFM_FLFM_FineOnly(  Path_s11c_unifor , Path_s31c_unifor , Data_06_CCD_RF   ,Flag_WFMPSFOnly  ,...
                                        P27_NIP_RefAr_Odd, P27_NIP_RefAr_Eve, P47_MLA_NumAdSim , P47_MLA_NumAd_RF,...
                                        Flag_Startpoint  , Flag_Finalpoint  , Object_33_ZdNum  , Object_35_ZCoor ,...
                                        Step_NIP_Finetune, Fl_01_obj, Ma_06_Mic, NA_01_obj, Ind01_obj, lambdaAir ,...
                                        Step_Propergation, NIP_SegSZ, dis_04_em, det_08MLA, dis_05_mc, lambdaLen ,...
                                        Flag_Profilesim  , P41_Fou_MLATra   , P42_Fou_MLAApt                     ,...
                                        Data_02_formDt   , Data_01_formIm   , Data_00_maxval)
    end
    for idxta = 1                                                          % Test                              
%     P51_Cam_PSFtst = zeros(51,51,27);
%     for idxk  = Flag_breakpoint:Object_33_NumZd                             % Wave propogation and CSF save     
%         Path_s31c_zdepth = [num2str(idxk,'%03d'),'_',num2str(Object_35_CoorZ(idxk)*1e6,'%+08.3f'),'um'];
%         load([                                          Path_s315_CCDCSF,'_',Path_s31c_zdepth,Data_02_formDt]);
%         P51_Cam_PSFtst(:,:,idxk) = P35_Imgcrop_centerS((abs(P50_Cam_CSFunc).^2),51);
%         disp(idxk)
%     end
%     P51_Cam_PSFtst2 = rescale(P51_Cam_PSFtst);
% 	figure,imshow(squeeze(P51_Cam_PSFtst2(26,:,:)))
%     figure,plot(1:27,squeeze(P51_Cam_PSFtst2(26,26,:)))
%     
%     PA0_PrL_CSFtst = zeros([size(PA0_PrL_CSFunc),27]);
%     for idxk  = Flag_breakpoint:Object_33_NumZd                             % Wave propogation and CSF save     
%         Path_s31c_zdepth = [num2str(idxk,'%03d'),'_',num2str(Object_35_CoorZ(idxk)*1e6,'%+08.3f'),'um'];
%         load([                                          Path_s31A_CSFPrf,'_',Path_s31c_zdepth,Data_02_formDt]);
%         PA0_PrL_CSFtst(:,:,idxk) = abs(PA0_PrL_CSFunc).^2;
%         disp(idxk)
%     end
%     PA0_PrL_CSFtst2 = rescale(PA0_PrL_CSFtst);
%     figure,imshow(PA0_PrL_CSFtst2(:,:,13)*10000)
%     PA0_PrL_CSFtst3 = PA0_PrL_CSFtst2(2000:2065,1:65,:);
%     PA0_PrL_CSFtst4 = PA0_PrL_CSFtst2(2000:2065,4265:4315,:);
%     figure,imshow(PA0_PrL_CSFtst3(:,:,13)+PA0_PrL_CSFtst3(:,:,22))
%     figure,imshow((PA0_PrL_CSFtst4(:,:,13)+PA0_PrL_CSFtst4(:,:,22))*100)
%     figure,imshow((PA0_PrL_CSFtst4(:,:,13)+PA0_PrL_CSFtst4(:,:,13))*100)
%     figure,imshow((PA0_PrL_CSFtst4(:,:,22)+PA0_PrL_CSFtst4(:,:,22))*100)
%     
%     
%     P31_Cam_PSFtst = zeros(27,27,27);
%     for idxk  = Flag_breakpoint:Object_33_NumZd                             % Wave propogation and CSF save     
%         Path_s31c_zdepth = [num2str(idxk,'%03d'),'_',num2str(Object_35_CoorZ(idxk)*1e6,'%+08.3f'),'um'];
%         load([                                          Path_s311_NIPodd,'_',Path_s31c_zdepth,Data_02_formDt]);
%         P31_Cam_PSFtst(:,:,idxk) = P35_Imgcrop_centerS((abs(P20_NIP_CSFOdd).^2),27);
%         disp(idxk)
%     end
%     P31_Cam_PSFtst2 = rescale(P31_Cam_PSFtst);
% 	figure,imshow(squeeze(P31_Cam_PSFtst2(13,:,:)))
%     figure,plot(1:27,squeeze(P31_Cam_PSFtst2(13,13,:)))
    
    end
%     tst2 = imbinarize(tst1);
%     [tstx,tsty]=ind2sub(size(tst2),find(tst2>0));
%     max(tstx)-min(tstx)
%     max(tsty)-min(tsty)
%% CSF&PSF calculation and data storage====================================HS-FLFM
    for idxsg = 1                                                          % Sampling parameter set HighSamp   
        Data_05HRifine = 1;     Data_05HRifine = round(Data_05HRifine);
        Data_05HDownRT = Ma_06_FLF/Ma_01_obj;                              % Downsampling ratio                
                                                                           % Mic & MLA & FLP characterization  
       [P27hNIP_RefAr_Odd,P27hNIP_RefAr_Eve,Data_06HCCD_DN  ,...
        P27hWFM_RefAd_Odd,P27hWFM_RefAd_Eve,Data_06HCCD_RF  ,...
        P35hLen_NumPd_DN ,P37hLen_NumPd_RF ,P37hLen_NumAd_RF,...
        P47hFou_NumAd_RF ,P47hMLA_NumAd_TP ,P47hMLA_NumAd_RF]...
      = H01_calcPSF_MatrixSize(                                              ...
        Ma_06_Mic, NA_01_obj, Pi_04_MLA, Dm_04_mic, Pi_05_cam, Num05_cam    ,...
        Data_05HDownRT  ,Data_05HRifine  ,Object_31_ZmFOV ,                  ...
        Theory_22_NatRd ,Theory_23_FouRd ,Theory_31_NumEl ,Theory_41_ResNL  ,...
        P291_NIP_Size_Ext,P292_NIP_Size_Wav,P293_NIP_Size_Num,P492_MLA_lens_Ext,...
        Flag_Simulation ,Flag_WFMPSFOnly ,Flag_simPSFfine ,P491_MLA_lens_Num,Flag_MLA_size_Odd)
        disp(['Size of PSF   = ' num2str(P27hNIP_RefAr_Odd) 'X' num2str(P27hNIP_RefAr_Odd) '' ]);
        disp(['Size of IMAGE = ' num2str(P47hMLA_NumAd_TP ) 'X' num2str(P47hMLA_NumAd_TP ) '' ]);
        disp(['Numb of layers= ' num2str(Object_33_ZdNum)                                  '' ]);
    end
    for idxta = 1                                                          % MLA pattern generated             
        if(Flag_MLA_grid_Hex==1)                                             % Mic & MLA & FLP generation        
            P41HFou_MLATra = I25_MLA_Modulation_SQU_Aperture_Num(                        ... 
                                     Fl_04_MLA       , k0             ,Data_06HCCD_RF   ,...
                                     P37hLen_NumPd_RF,P37hLen_NumPd_RF,P37hLen_NumAd_RF ,...
                                     P47hMLA_NumAd_TP,P47hFou_NumAd_RF,P490_MLA_Beam_Rat,...
                                     Flag_Lens_Tra_Cir ,Flag_Lens_On_axis ,0                ,...
                                     Flag_Lens_All_Use ,Flag_MLA_grid_Inv);
            P42HFou_MLAApt = I25_MLA_Modulation_SQU_Aperture_Num(                        ...
                                     Fl_04_MLA       , k0             ,Data_06HCCD_RF   ,...
                                     P37hLen_NumPd_RF,P37hLen_NumAd_RF,P37hLen_NumAd_RF ,...
                                     P47hMLA_NumAd_TP,P47hFou_NumAd_RF,P490_MLA_Beam_Rat,...
                                     Flag_Lens_Apt_Cir ,Flag_Lens_On_axis ,1                ,...
                                     Flag_Lens_All_Use ,Flag_MLA_grid_Inv);
        else
            P41HFou_MLATra = I25_MLA_Modulation_SQU_Aperture_Num(                        ...  
                                     Fl_04_MLA       , k0             ,Data_06HCCD_RF   ,...
                                     P37hLen_NumPd_RF,P37hLen_NumPd_RF,P37hLen_NumAd_RF ,...
                                     P47hMLA_NumAd_TP,P47hFou_NumAd_RF,P490_MLA_Beam_Rat,...
                                     Flag_Lens_Tra_Cir ,Flag_Lens_On_axis ,0                ,...
                                     Flag_Lens_All_Use);
            P42HFou_MLAApt = I25_MLA_Modulation_SQU_Aperture_Num(                        ...
                                     Fl_04_MLA       , k0             ,Data_06HCCD_RF   ,...
                                     P37hLen_NumPd_RF,P37hLen_NumAd_RF,P37hLen_NumAd_RF ,...
                                     P47hMLA_NumAd_TP,P47hFou_NumAd_RF,P490_MLA_Beam_Rat,...
                                     Flag_Lens_Apt_Cir ,Flag_Lens_On_axis ,1                ,...
                                     Flag_Lens_All_Use);
        end
    end
    for idxta = 1                                                          % Save path name set                
        Path_s030Hsample =['P'  ,num2str(Pi_05_cam      *1e6) 'um_',...
                           'RF' ,num2str(Data_05HRifine *1e0)   '_',...
                           'DN' ,num2str(Data_05HDownRT *1e0)   '_',...
                           'B'  ,num2str(Data_00_bit        )   '_'];
       
        Path_s00Hneotime = char(datetime('now','TimeZone','local','Format','yyyyMMdd_HHmm'));
        Path_s31b_update = [File_31_FLF_PSFsim_save,'\',Path_s00Hneotime];mkdir(Path_s31b_update)
        Path_s31c_unifor = [Path_s31b_update,'\',...
                    'FLF_', Path_s020_FouLFM, Path_s040_zrange, Path_s030Hsample,...
                    'SPD' , num2str(P37hLen_NumAd_RF)   ];
    end
        FlagHbreakpoint = 1
    for idxta = 1                                                          % Wave propogation                  
        close all;      clc;                                  disp('Start Calculating CSF...');          
        % Wave propogation                  
        H45_calcPSF_FLFM_Only_Square(Path_s31c_unifor , Data_05HRifine   , Data_06HCCD_RF                    ,...
                                     P27hNIP_RefAr_Odd, P27hNIP_RefAr_Eve, P47hMLA_NumAd_TP, P47hMLA_NumAd_RF,...
                                     FlagHbreakpoint  , Object_33hNumZd  , Object_35_ZCoor                   ,...
                                     Step_NIP_Finetune, Fl_01_obj, Ma_06_Mic, NA_01_obj, Ind01_obj, lambdaAir   ,...
                                     Step_Propergation, NIP_SegSZ  , dis_04_em , det_08MLA , dis_05_mc , lambdaLen   ,...
                                     Flag_Simulation  , P41HFou_MLATra, P42HFou_MLAApt, ...
                                     Data_02_formDt   , Data_01_formIm, Data_00_maxval)
    end
    
%% System Charaterization==================================================LS-FLFM -200~+200
    for idxsg = 1                                                          % Object parameters set             
        Object_31_ZuFOV  = + 200.000*10^-6;                                % Get
        Object_31_ZlFOV  = - 200.000*10^-6;                                % Get
        Object_32_Z_stp  =   000.400*10^-6;                                % Get
        
       [Object_31_ZmFOV,Object_33_ZuNum,Object_33_ZlNum,...
        Object_33_ZdNum,Object_34_Z_Ind,Object_35_ZCoor] = S01_Coord_create_ud(...
        Object_31_ZuFOV,Object_31_ZlFOV,Object_32_Z_stp);
    end
    for idxsg = 1                                                          % Ray tracing figure set and draw   
        Para_Raytrace_step_xx = 0.05;
        Para_Raytrace_Ray_num = 35;
        Para_draw_axis        = 0;
        
        Ini_coorr = 0.0;
        Ini_coorz = 0.5;
        F21_ray_tracing_CPU_20191221(dis_01_oo ,Fl_01_obj,Dm_01_obj,...
                                     dis_02_ot ,Fl_02_tub,Dm_02_tub,...
                                     dis_03_te ,Fl_03_ent,Dm_03_ent,...
                                     dis_04_em ,Fl_04_MLA,Dm_04_mic,...
                                     dis_05_mc ,Pi_04_MLA,Dm_04_MLA,...
                                     Ma_01_obj,NA_01_obj,Pi_05_cam,...
                                     Para_Raytrace_step_xx,Para_Raytrace_Ray_num,Ini_coorr,...
                                     Flag_Lens_On_axis    ,Para_draw_axis       ,Ini_coorz,...
                                     File_90_RayTracingsav,Data_01_formIm)
    end
    for idxta = 1                                                          % Theoretical predicted Character   
        %FLFM system AND FLFM system-imaging
       [Ma_06_Mic,Ma_06_FLF,fn_06_FLF                  ,...
        fn_06_sub,Ma_07_img                            ,...
        Theory_21_BakRd,Theory_22_NatRd                ,...
        Theory_23_FouRd,Theory_31_RatEl,Theory_31_NumEl,...
        Theory_41_ResNL,Theory_41_ResNA                ,...
        Theory_51_FWHML,Theory_52_FWHMA                ,...
        Theory_61_ResR0,Theory_62_ResZ0,Theory_63_ResZE,...
        Theory_71_FOVR0                                ,...
        Theory_72_DOFZ0,Theory_73_FOVZu,Theory_74_FOVZl,...
        Theory_32_NumEl,Theory_73_FOV_R,Theory_74_DOF_Z,...
        Theory_66_Res_R,Theory_67_Res_Z,Theory_68_ResZR] =  ...
        F30_FLFsys_Characters(Fl_01_obj,NA_01_obj,Ma_01_obj,...
                              Fl_01_tub,Fl_02_tub          ,...
                              Fl_03_ent,Fl_07_img          ,...
                              Fl_04_MLA,Dm_04_mic,Pi_04_MLA,...
                              fn_01_obj,fn_04_MLA,lambdaAir,...
                              del_05_mc,del_03_te,del_04_em,...
                              Object_34_Z_Ind);
        
       [Path_s010_objlam,Path_s020_FouLFM,Path_s040_zrange] = ...
        F31_FLFsys_para_Lable(Ma_01_obj,NA_01_obj,lambdaAir  ,...
                              Fl_02_tub,Fl_03_ent            ,...
                              Dm_04_mic,Pi_04_MLA,fn_04_MLA  ,...
                              Object_31_ZlFOV,Object_31_ZuFOV,Object_32_Z_stp);
    end
    close all
%% CSF&PSF calculation and data storage====================================LS-FLFM
    for idxsg = 1                                                          % Sampling parameter set            
        P293_NIP_Size_Num = 1451;
        P492_MLA_lens_Ext = 2;
        
        Flag_Profilesim= 0;                                                % profile simulatn, piont_sim = 1
        NIP_SegSZ      = 800;
        Data_05_Refine = 2;
        Data_05_DownRT = 1;                                                % Downsampling ratio
                                                                           % Mic & MLA & FLP characterization  
       [Data_06_CCD_DN   ,Data_06_CCD_RF   ,...
        P27_NIP_RefAr_Odd,P27_NIP_RefAr_Eve,...
        P27_WFM_RefAd_Odd,P27_WFM_RefAd_Eve,...
        P35_Len_NumPd_DN ,P37_Len_NumPd_RF ,P37_Len_NumAd_RF,...
        P47_Fou_NumAd_RF ,P47_MLA_NumAdSim ,P47_MLA_NumAd_RF,...
        Path_s031Lsample ,Path_s033Lsample                  ]...
      = F32_FLFsys_SampleL(                                                     ...
        Ma_06_Mic, NA_01_obj, Pi_04_MLA, Dm_04_mic, Pi_05_cam, Num05_cam       ,...
        Data_05_DownRT   ,Data_05_Refine   ,Object_31_ZmFOV  ,                  ...
        Theory_22_NatRd  ,Theory_23_FouRd  ,Theory_31_NumEl  ,Theory_41_ResNL  ,...
        P291_NIP_Size_Ext,P292_NIP_Size_Wav,P293_NIP_Size_Num,P492_MLA_lens_Ext,...
        Flag_Simulation  ,Flag_WFMPSFOnly  ,Flag_simPSFfine  ,P491_MLA_lens_Num,Flag_MLA_size_Odd)
                                                                           % Mic & MLA & FLP characterization  
        disp(['Size of PSF   = ' num2str(P27_NIP_RefAr_Odd) 'X' num2str(P27_NIP_RefAr_Odd) '' ]);
        disp(['Size of IMAGE = ' num2str(P47_MLA_NumAdSim ) 'X' num2str(P47_MLA_NumAdSim ) '' ]);
        disp(['Numb of layers= ' num2str(Object_33_ZdNum)                                  '' ]);
    end
    for idxta = 1                                                          % MLA pattern generated             
        if(Flag_MLA_grid_Hex==1)
            P41_Fou_MLATra = I26_MLA_Modulation_HEX_Aperture_Num(                       ... 
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF  ,...
                                     P37_Len_NumPd_RF,P37_Len_NumPd_RF,P37_Len_NumAd_RF,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,1.93            ,...
                                     Flag_Lens_Tra_Cir ,Flag_Lens_On_axis ,0,...
                                     Flag_Lens_All_Use ,Flag_MLA_grid_Inv);
            P42_Fou_MLAApt = I26_MLA_Modulation_HEX_Aperture_Num(                       ...
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF  ,...
                                     P37_Len_NumPd_RF,P37_Len_NumAd_RF,P37_Len_NumAd_RF,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,1.93            ,...
                                     Flag_Lens_Apt_Cir ,Flag_Lens_On_axis ,1               ,...
                                     Flag_Lens_All_Use ,Flag_MLA_grid_Inv);
        else
            P41_Fou_MLATra = I25_MLA_Modulation_SQU_Aperture_Num(                       ...  
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF  ,...
                                     P37_Len_NumPd_RF,P37_Len_NumPd_RF,P37_Len_NumAd_RF,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,P490_MLA_Beam_Rat ,...
                                     Flag_Lens_Tra_Cir ,Flag_Lens_On_axis ,0               ,...
                                     Flag_Lens_All_Use);
            P42_Fou_MLAApt = I25_MLA_Modulation_SQU_Aperture_Num(                        ...
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF   ,...
                                     P37_Len_NumPd_RF,P37_Len_NumAd_RF,P37_Len_NumAd_RF ,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,P490_MLA_Beam_Rat,...
                                     Flag_Lens_Apt_Cir ,Flag_Lens_On_axis ,1            ,...
                                     Flag_Lens_All_Use);
        end
    end
    for idxta = 1                                                          % Save path name set                
        Path_s000neotime = char(datetime('now','TimeZone','local','Format','yyMMdd_HHmm'));
        Path_s11b_update = [File_11_WFMPSF_SimSav,Path_s000neotime];   mkdir(Path_s11b_update)
        Path_s11c_unifor = [Path_s11b_update,'\',...
                     'WFM_',Path_s010_objlam, Path_s040_zrange, Path_s031Lsample];
        Path_s31b_update = [File_31_FLFPSF_SimSav,Path_s000neotime];   mkdir(Path_s31b_update)
        Path_s31c_unifor = [Path_s31b_update,'\',...
                     'FLF_',Path_s020_FouLFM, Path_s040_zrange, Path_s033Lsample];
    end
    for idxta = 1                                                          % Wave propogation                  
        close all;      clc;        disp('Start Calculating CSF...');
        % Wave propogation                                                 
        Flag_breakpoint = 1
        Flag_Startpoint = 129
        Flag_Finalpoint = 1001
                                  
        H46_calcPSF_WFM_FLFM_FineOnly(  Path_s11c_unifor , Path_s31c_unifor , Data_06_CCD_RF   ,Flag_WFMPSFOnly  ,...
                                        P27_NIP_RefAr_Odd, P27_NIP_RefAr_Eve, P47_MLA_NumAdSim , P47_MLA_NumAd_RF,...
                                        Flag_Startpoint  , Flag_Finalpoint  , Object_33_ZdNum  , Object_35_ZCoor ,...
                                        Step_NIP_Finetune, Fl_01_obj, Ma_06_Mic, NA_01_obj, Ind01_obj, lambdaAir ,...
                                        Step_Propergation, NIP_SegSZ, dis_04_em, det_08MLA, dis_05_mc, lambdaLen ,...
                                        Flag_Profilesim  , P41_Fou_MLATra   , P42_Fou_MLAApt                     ,...
                                        Data_02_formDt   , Data_01_formIm   , Data_00_maxval)
        
        H47_calcPSF_WFM_FLFM_Desampling(Path_s11c_unifor , Path_s31c_unifor , Data_05_Refine  ,...
                                        P27_WFM_RefAd_Odd, P27_WFM_RefAd_Eve, P47_MLA_NumAd_RF,...
                                        Object_33_ZdNum  , Object_35_ZCoor  ,                  ...
                                        Data_02_formDt   , Data_01_formIm   ,                  ...
                                        Flag_Simulation  , Flag_WFMPSFOnly  , Flag_breakpoint)
        S65_Imsave_B16_MIP_3D_Col(Image_Path,Image_form,Image_Data,Index_Col,Flag_File)
                                    
    end
%% CSF&PSF calculat-ion and data storage===================================LS-FLFM Addition
    for idxsg = 1                                                          % Sampling parameter set            
        P293_NIP_Size_Num = 1551;
        P492_MLA_lens_Ext = 2;
        NIP_SegSZ = 800;
        Data_05_Refine = 2;
        Data_05_DownRT = 1;                                                % Downsampling ratio
                                                                           % Mic & MLA & FLP characterization  
       [Data_06_CCD_DN   ,Data_06_CCD_RF   ,...
        P27_NIP_RefAr_Odd,P27_NIP_RefAr_Eve,...
        P27_WFM_RefAd_Odd,P27_WFM_RefAd_Eve,...
        P35_Len_NumPd_DN ,P37_Len_NumPd_RF ,P37_Len_NumAd_RF,...
        P47_Fou_NumAd_RF ,P47_MLA_NumAdSim ,P47_MLA_NumAd_RF,...
        Path_s031Lsample ,Path_s033Lsample                  ]...
      = F32_FLFsys_SampleL(                                                     ...
        Ma_06_Mic, NA_01_obj, Pi_04_MLA, Dm_04_mic, Pi_05_cam, Num05_cam       ,...
        Data_05_DownRT   ,Data_05_Refine   ,Object_31_ZmFOV  ,                  ...
        Theory_22_NatRd  ,Theory_23_FouRd  ,Theory_31_NumEl  ,Theory_41_ResNL  ,...
        P291_NIP_Size_Ext,P292_NIP_Size_Wav,P293_NIP_Size_Num,P492_MLA_lens_Ext,...
        Flag_Simulation  ,Flag_WFMPSFOnly  ,Flag_simPSFfine  ,P491_MLA_lens_Num,Flag_MLA_size_Odd)
                                                                           % Mic & MLA & FLP characterization  
        disp(['Size of PSF   = ' num2str(P27_NIP_RefAr_Odd) 'X' num2str(P27_NIP_RefAr_Odd) '' ]);
        disp(['Size of IMAGE = ' num2str(P47_MLA_NumAdSim ) 'X' num2str(P47_MLA_NumAdSim ) '' ]);
        disp(['Numb of layers= ' num2str(Object_33_ZdNum)                                  '' ]);
    end
    for idxta = 1                                                          % MLA pattern generated             
        if(Flag_MLA_grid_Hex==1)
            P41_Fou_MLATra = I26_MLA_Modulation_HEX_Aperture_Num(                       ... 
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF  ,...
                                     P37_Len_NumPd_RF,P37_Len_NumPd_RF,P37_Len_NumAd_RF,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,1.93            ,...
                                     Flag_Lens_Tra_Cir ,Flag_Lens_On_axis ,0,...
                                     Flag_Lens_All_Use ,Flag_MLA_grid_Inv);
            P42_Fou_MLAApt = I26_MLA_Modulation_HEX_Aperture_Num(                       ...
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF  ,...
                                     P37_Len_NumPd_RF,P37_Len_NumAd_RF,P37_Len_NumAd_RF,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,1.93            ,...
                                     Flag_Lens_Apt_Cir ,Flag_Lens_On_axis ,1               ,...
                                     Flag_Lens_All_Use ,Flag_MLA_grid_Inv);
        else
            P41_Fou_MLATra = I25_MLA_Modulation_SQU_Aperture_Num(                       ...  
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF  ,...
                                     P37_Len_NumPd_RF,P37_Len_NumPd_RF,P37_Len_NumAd_RF,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,P490_MLA_Beam_Rat ,...
                                     Flag_Lens_Tra_Cir ,Flag_Lens_On_axis ,0               ,...
                                     Flag_Lens_All_Use);
            P42_Fou_MLAApt = I25_MLA_Modulation_SQU_Aperture_Num(                        ...
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF   ,...
                                     P37_Len_NumPd_RF,P37_Len_NumAd_RF,P37_Len_NumAd_RF ,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,P490_MLA_Beam_Rat,...
                                     Flag_Lens_Apt_Cir ,Flag_Lens_On_axis ,1            ,...
                                     Flag_Lens_All_Use);
        end
    end
    for idxta = 1                                                          % Save path name set                
        Path_s000neotime = char(datetime('now','TimeZone','local','Format','yyMMdd_HHmm'));
        Path_s11b_update = [File_11_WFMPSF_SimSav,Path_s000neotime];   mkdir(Path_s11b_update)
        Path_s11c_unifor = [Path_s11b_update,'\',...
                     'WFM_',Path_s010_objlam, Path_s040_zrange, Path_s031Lsample];
        Path_s31b_update = [File_31_FLFPSF_SimSav,Path_s000neotime];   mkdir(Path_s31b_update)
        Path_s31c_unifor = [Path_s31b_update,'\',...
                     'FLF_',Path_s020_FouLFM, Path_s040_zrange, Path_s033Lsample];
    end
    for idxta = 1                                                          % Wave propogation                  
        close all;      clc;        disp('Start Calculating CSF...');
        % Wave propogation                                                 
        Flag_breakpoint = 876
        Flag_Startpoint = 1
        Flag_Finalpoint = 26
                                  
        H46_calcPSF_WFM_FLFM_FineOnly(  Path_s11c_unifor , Path_s31c_unifor , Data_06_CCD_RF   ,Flag_WFMPSFOnly  ,...
                                        P27_NIP_RefAr_Odd, P27_NIP_RefAr_Eve, P47_MLA_NumAdSim , P47_MLA_NumAd_RF,...
                                        Flag_Startpoint  , Flag_Finalpoint  , Object_33_ZdNum  , Object_35_ZCoor ,...
                                        Step_NIP_Finetune, Fl_01_obj, Ma_06_Mic, NA_01_obj, Ind01_obj, lambdaAir ,...
                                        Step_Propergation, NIP_SegSZ, dis_04_em, det_08MLA, dis_05_mc, lambdaLen ,...
                                        Flag_Profilesim  , P41_Fou_MLATra   , P42_Fou_MLAApt                     ,...
                                        Data_02_formDt   , Data_01_formIm   , Data_00_maxval)
        
        Flag_breakpoint = 1
        H47_calcPSF_WFM_FLFM_Desampling(Path_s11c_unifor , Path_s31c_unifor , Data_05_Refine  ,...
                                        P27_WFM_RefAd_Odd, P27_WFM_RefAd_Eve, P47_MLA_NumAd_RF,...
                                        Object_33_ZdNum  , Object_35_ZCoor  ,                  ...
                                        Data_02_formDt   , Data_01_formIm   ,                  ...
                                        Flag_Simulation  , Flag_WFMPSFOnly  , Flag_breakpoint)
    end

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    