clear all;  close all;  clc;
addpath(genpath('..\Util_Summary'))
addpath(genpath('..\Color'))
%% General Parameter Set============================================
    for idxsg = 1	                                                       % Save path name   set              
        File_00_path = '..\';                                
        File_00_Dash = '\'; 
        File_00_Line = '_'; 
        File_01_sav = 'sav'; 
        File_02_raw = 'raw'; 
        File_04_rec = 'rec'; 
        File_06_pro = 'pro'; 
        File_0a_sim = 'sim'; 
        File_0b_exp = 'exp'; 
        File_0c_bkg = 'bkg'; 

        File_10_WFMPSF        = '1WFMPSF'; 
        File_11_WFMPSF_SimSav = [File_00_path,File_10_WFMPSF,'_1',File_0a_sim,File_01_sav];mkdir(File_11_WFMPSF_SimSav);
        File_12_WFMPSF_ExpRaw = [File_00_path,File_10_WFMPSF,'_2',File_0b_exp,File_02_raw];mkdir(File_12_WFMPSF_ExpRaw);
        File_13_WFMPSF_BkgRaw = [File_00_path,File_10_WFMPSF,'_3',File_0c_bkg,File_02_raw];mkdir(File_13_WFMPSF_BkgRaw);
        File_14_WFMPSF_SimRec = [File_00_path,File_10_WFMPSF,'_4',File_0a_sim,File_04_rec];mkdir(File_14_WFMPSF_SimRec);
        File_15_WFMPSF_ExpRec = [File_00_path,File_10_WFMPSF,'_5',File_0b_exp,File_04_rec];mkdir(File_15_WFMPSF_ExpRec);
        File_16_WFMPSF_ExpPro = [File_00_path,File_10_WFMPSF,'_6',File_0b_exp,File_06_pro];
        
        File_20_WFMImg        = '2WFMImg'; 
        File_21_WFMImg_SimSav = [File_00_path,File_20_WFMImg,'_1',File_0a_sim,File_01_sav];mkdir(File_21_WFMImg_SimSav);
        File_22_WFMImg_ExpRaw = [File_00_path,File_20_WFMImg,'_2',File_0b_exp,File_02_raw];mkdir(File_22_WFMImg_ExpRaw);
        File_23_WFMImg_BkgRaw = [File_00_path,File_20_WFMImg,'_3',File_0c_bkg,File_02_raw];mkdir(File_23_WFMImg_BkgRaw);
        File_24_WFMImg_SimRec = [File_00_path,File_20_WFMImg,'_4',File_0a_sim,File_04_rec];mkdir(File_24_WFMImg_SimRec);
        File_25_WFMImg_ExpRec = [File_00_path,File_20_WFMImg,'_5',File_0b_exp,File_04_rec];mkdir(File_25_WFMImg_ExpRec);
        File_26_WFMImg_ExpPro = [File_00_path,File_20_WFMImg,'_6',File_0b_exp,File_06_pro];
        
        File_30_FLFPSF        = '3FLFPSF'; 
        File_31_FLFPSF_SimSav = [File_00_path,File_30_FLFPSF,'_1',File_0a_sim,File_01_sav];mkdir(File_31_FLFPSF_SimSav);
        File_32_FLFPSF_ExpRaw = [File_00_path,File_30_FLFPSF,'_2',File_0b_exp,File_02_raw];mkdir(File_32_FLFPSF_ExpRaw);
        File_33_FLFPSF_BkgRaw = [File_00_path,File_30_FLFPSF,'_3',File_0c_bkg,File_02_raw];mkdir(File_33_FLFPSF_BkgRaw);
        File_34_FLFPSF_SimRec = [File_00_path,File_30_FLFPSF,'_4',File_0a_sim,File_04_rec];
        File_35_FLFPSF_ExpRec = [File_00_path,File_30_FLFPSF,'_5',File_0b_exp,File_04_rec];
        File_36_FLFPSF_ExpPro = [File_00_path,File_30_FLFPSF,'_6',File_0b_exp,File_06_pro];
        
        File_40_FLFImg        = '4FLFImg'; 
        File_41_FLFImg_SimSav = [File_00_path,File_40_FLFImg,'_1',File_0a_sim,File_01_sav];mkdir(File_41_FLFImg_SimSav);
        File_42_FLFImg_ExpRaw = [File_00_path,File_40_FLFImg,'_2',File_0b_exp,File_02_raw];mkdir(File_42_FLFImg_ExpRaw);
        File_43_FLFImg_BkgRaw = [File_00_path,File_40_FLFImg,'_3',File_0c_bkg,File_02_raw];mkdir(File_43_FLFImg_BkgRaw);
        File_44_FLFImg_SimRec = [File_00_path,File_40_FLFImg,'_4',File_0a_sim,File_04_rec];
        File_45_FLFImg_ExpRec = [File_00_path,File_40_FLFImg,'_5',File_0b_exp,File_04_rec];
        File_46_FLFPSF_ExpPro = [File_00_path,File_40_FLFImg,'_6',File_0b_exp,File_06_pro];
        
        File_50_FLFVid        = '5FLFVid'; 
        File_51_FLFVid_SimSav = [File_00_path,File_50_FLFVid,'_1',File_0a_sim,File_01_sav];mkdir(File_51_FLFVid_SimSav);
        File_52_FLFVid_ExpRaw = [File_00_path,File_50_FLFVid,'_2',File_0b_exp,File_02_raw];mkdir(File_52_FLFVid_ExpRaw);
        File_53_FLFVid_BkgRaw = [File_00_path,File_50_FLFVid,'_3',File_0c_bkg,File_02_raw];mkdir(File_53_FLFVid_BkgRaw);
        File_54_FLFVid_SimRec = [File_00_path,File_50_FLFVid,'_4',File_0a_sim,File_04_rec];
        File_55_FLFVid_ExpRec = [File_00_path,File_50_FLFVid,'_5',File_0b_exp,File_04_rec];
        File_56_FLFVid_ExpPro = [File_00_path,File_50_FLFVid,'_6',File_0b_exp,File_06_pro];
        
        File_90_RayTracingsav = [File_00_path,'\','90_Ray_Tracingsave'];mkdir(File_90_RayTracingsav);
    end
    for idxsg = 1	                                                       % Save path name   set              
        Path_n415_Ground = '5_Ground';
        Path_n417_WFMImg = '7_WFMImg';
        Path_n418_FLFImg = '8_FLFImg';
        Path_n419_FLFrez = '9_FLFrez';
    end
    for idxsg = 1                                                          % Image  parameter set              
        Data_00_bit     = 16    ;                                          %get
        Data_00_maxval  = 2^Data_00_bit-1;
        Data_01_formIm  = '.tif';                                          %get
        Data_01_formVd  = '.avi';                                          %get
        Data_02_formDt  = '.mat';                                          %get
        Data_04_smoothn = 1;                                               %Get?Recons_00_NUMd
        Data_04_Oper_sm = fspecial('gaussian',[Data_04_smoothn Data_04_smoothn],0.6);
    end
%% System parameter set 016X_new_300/200
    for idxsg = 1                                                          % System parameter  set 016X_new_300/200 
       [Fl_01_obj,Dm_01_obj,fn_01_obj          ,...
        Fl_01_tub,Ma_01_obj,NA_01_obj,Ind01_obj,...
        Fl_02_tub,Dm_02_tub,fn_02_tub          ,...
        Fl_03_ent,Dm_03_ent,fn_03_ent          ,...
        Fl_04_MLA,Dm_04_MLA,fn_04_MLA,det_08MLA,...
        Fl_04bMLA,Dm_04_mic,Pi_04_MLA,Ind04_MLA,...
        Num05_cam,Dm_05_cam,Pi_05_cam          ,...
        Fl_07_img,Dm_07_img,fn_07_img          ,...
        lambdaAir,lambdaLen,k0       ,kn       ,...
        del_01_oo,del_02_ot,del_03_te,del_04_em,...
        del_05_mc,dell05_mc,del_06_ti,del_07_ec,...
        dis_01_oo,dis_02_ot,dis_03_te,dis_04_em,...
        dis_05_mc,dis_06_ti,dis_07_ec] = F13_FLFsys_para_016XWV2_680nm();
        
                                                                           % Simulation parameters set
	   [Step_NIP_Finetune,Step_Propergation,...
        Flag_WFMPSFOnly  ,Flag_Simulation  ,...
        Flag_simPSFfine  ,Flag_Profilesim  ,...
        P291_NIP_Size_Ext,P292_NIP_Size_Wav,P293_NIP_Size_Num,...
        P490_MLA_Beam_Rat,P491_MLA_lens_Num,...
        P492_MLA_lens_Ext,Flag_MLA_size_Odd,...
        Flag_MLA_grid_Hex,Flag_MLA_grid_Inv,...
        Flag_Lens_On_axis,Flag_Lens_All_Use,...
        Flag_Lens_Tra_Cir,Flag_Lens_Apt_Cir,...
        Flag_Aperture ] = F13_FLFsys_para_016XWV2_Sim();
    end
%% System Charaterization==================================================
    for idxsg = 1                                                          % Object parameters set             
        Object_31_ZuFOV  = + 200.000*10^-6;                                % Get
        Object_31_ZlFOV  = - 200.000*10^-6;                                % Get
        Object_32_Z_stp  =   000.400*10^-6;                                % Get
        
       [Object_31_ZmFOV,Object_33_ZuNum,Object_33_ZlNum,...
        Object_33_ZdNum,Object_34_Z_Ind,Object_35_ZCoor] = S01_Coord_create_ud(...
        Object_31_ZuFOV,Object_31_ZlFOV,Object_32_Z_stp);
    end
    for idxsg = 1                                                          % Ray tracing figure set and draw   
        Para_Raytrace_step_xx = 0.05;
        Para_Raytrace_Ray_num = 35;
        Para_draw_axis        = 0;
        
        Ini_coorr = 0.0;
        Ini_coorz = 0.5;
        F21_ray_tracing_CPU_20191221(dis_01_oo ,Fl_01_obj,Dm_01_obj,...
                                     dis_02_ot ,Fl_02_tub,Dm_02_tub,...
                                     dis_03_te ,Fl_03_ent,Dm_03_ent,...
                                     dis_04_em ,Fl_04_MLA,Dm_04_mic,...
                                     dis_05_mc ,Pi_04_MLA,Dm_04_MLA,...
                                     Ma_01_obj,NA_01_obj,Pi_05_cam,...
                                     Para_Raytrace_step_xx,Para_Raytrace_Ray_num,Ini_coorr,...
                                     Flag_Lens_On_axis    ,Para_draw_axis       ,Ini_coorz,...
                                     File_90_RayTracingsav,Data_01_formIm)
    end
    for idxta = 1                                                          % Theoretical predicted Character   
        %FLFM system AND FLFM system-imaging
       [Ma_06_Mic,Ma_06_FLF,fn_06_FLF                  ,...
        fn_06_sub,Ma_07_img                            ,...
        Theory_21_BakRd,Theory_22_NatRd                ,...
        Theory_23_FouRd,Theory_31_RatEl,Theory_31_NumEl,...
        Theory_41_ResNL,Theory_41_ResNA                ,...
        Theory_51_FWHML,Theory_52_FWHMA                ,...
        Theory_61_ResR0,Theory_62_ResZ0,Theory_63_ResZE,...
        Theory_71_FOVR0                                ,...
        Theory_72_DOFZ0,Theory_73_FOVZu,Theory_74_FOVZl,...
        Theory_32_NumEl,Theory_73_FOV_R,Theory_74_DOF_Z,...
        Theory_66_Res_R,Theory_67_Res_Z,Theory_68_ResZR] =  ...
        F30_FLFsys_Characters(Fl_01_obj,NA_01_obj,Ma_01_obj,...
                              Fl_01_tub,Fl_02_tub          ,...
                              Fl_03_ent,Fl_07_img          ,...
                              Fl_04_MLA,Dm_04_mic,Pi_04_MLA,...
                              fn_01_obj,fn_04_MLA,lambdaAir,...
                              del_05_mc,del_03_te,del_04_em,...
                              Object_34_Z_Ind);
        
       [Path_s010_objlam,Path_s020_FouLFM,Path_s040_zrange] = ...
        F31_FLFsys_para_Lable(Ma_01_obj,NA_01_obj,lambdaAir  ,...
                              Fl_02_tub,Fl_03_ent            ,...
                              Dm_04_mic,Pi_04_MLA,fn_04_MLA  ,...
                              Object_31_ZlFOV,Object_31_ZuFOV,Object_32_Z_stp);
    end
close all
%% CSF&PSF calculation and data storage====================================LS-FLFM
    for idxsg = 1                                                          % Sampling parameter set            
        P293_NIP_Size_Num = 1451;
        P492_MLA_lens_Ext = 2;
        
        Flag_Profilesim= 0;                                                % profile simulatn, piont_sim = 1
        NIP_SegSZ      = 800;
        Data_05_Refine = 2;
        Data_05_DownRT = 1;                                                % Downsampling ratio
                                                                           % Mic & MLA & FLP characterization  
       [Data_06_CCD_DN   ,Data_06_CCD_RF   ,...
        P27_NIP_RefAr_Odd,P27_NIP_RefAr_Eve,...
        P27_WFM_RefAd_Odd,P27_WFM_RefAd_Eve,...
        P35_Len_NumPd_DN ,P37_Len_NumPd_RF ,P37_Len_NumAd_RF,...
        P47_Fou_NumAd_RF ,P47_MLA_NumAdSim ,P47_MLA_NumAd_RF,...
        Path_s031Lsample ,Path_s033Lsample                  ]...
      = F32_FLFsys_SampleL(                                                     ...
        Ma_06_Mic, NA_01_obj, Pi_04_MLA, Dm_04_mic, Pi_05_cam, Num05_cam       ,...
        Data_05_DownRT   ,Data_05_Refine   ,Object_31_ZmFOV  ,                  ...
        Theory_22_NatRd  ,Theory_23_FouRd  ,Theory_31_NumEl  ,Theory_41_ResNL  ,...
        P291_NIP_Size_Ext,P292_NIP_Size_Wav,P293_NIP_Size_Num,P492_MLA_lens_Ext,...
        Flag_Simulation  ,Flag_WFMPSFOnly  ,Flag_simPSFfine  ,P491_MLA_lens_Num,Flag_MLA_size_Odd)
                                                                           % Mic & MLA & FLP characterization  
        disp(['Size of PSF   = ' num2str(P27_NIP_RefAr_Odd) 'X' num2str(P27_NIP_RefAr_Odd) '' ]);
        disp(['Size of IMAGE = ' num2str(P47_MLA_NumAdSim ) 'X' num2str(P47_MLA_NumAdSim ) '' ]);
        disp(['Numb of layers= ' num2str(Object_33_ZdNum)                                  '' ]);
    end
    for idxta = 1                                                          % MLA pattern generated             
        if(Flag_MLA_grid_Hex==1)
            P41_Fou_MLATra = I26_MLA_Modulation_HEX_Aperture_Num(                       ... 
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF  ,...
                                     P37_Len_NumPd_RF,P37_Len_NumPd_RF,P37_Len_NumAd_RF,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,1.93            ,...
                                     Flag_Lens_Tra_Cir ,Flag_Lens_On_axis ,0,...
                                     Flag_Lens_All_Use ,Flag_MLA_grid_Inv);
            P42_Fou_MLAApt = I26_MLA_Modulation_HEX_Aperture_Num(                       ...
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF  ,...
                                     P37_Len_NumPd_RF,P37_Len_NumAd_RF,P37_Len_NumAd_RF,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,1.93            ,...
                                     Flag_Lens_Apt_Cir ,Flag_Lens_On_axis ,1               ,...
                                     Flag_Lens_All_Use ,Flag_MLA_grid_Inv);
        else
            P41_Fou_MLATra = I25_MLA_Modulation_SQU_Aperture_Num(                       ...  
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF  ,...
                                     P37_Len_NumPd_RF,P37_Len_NumPd_RF,P37_Len_NumAd_RF,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,P490_MLA_Beam_Rat ,...
                                     Flag_Lens_Tra_Cir ,Flag_Lens_On_axis ,0               ,...
                                     Flag_Lens_All_Use);
            P42_Fou_MLAApt = I25_MLA_Modulation_SQU_Aperture_Num(                        ...
                                     Fl_04_MLA       , k0             ,Data_06_CCD_RF   ,...
                                     P37_Len_NumPd_RF,P37_Len_NumAd_RF,P37_Len_NumAd_RF ,...
                                     P47_MLA_NumAdSim,P47_Fou_NumAd_RF,P490_MLA_Beam_Rat,...
                                     Flag_Lens_Apt_Cir ,Flag_Lens_On_axis ,1            ,...
                                     Flag_Lens_All_Use);
        end
    end
    for idxta = 1                                                          % Save path name set                
        Path_s000neotime = char(datetime('now','TimeZone','local','Format','yyMMdd_HHmm'));
        Path_s11b_update = [File_11_WFMPSF_SimSav,Path_s000neotime];   mkdir(Path_s11b_update)
        Path_s11c_unifor = [Path_s11b_update,'\',...
                     'WFM_',Path_s010_objlam, Path_s040_zrange, Path_s031Lsample];
        Path_s31b_update = [File_31_FLFPSF_SimSav,Path_s000neotime];   mkdir(Path_s31b_update)
        Path_s31c_unifor = [Path_s31b_update,'\',...
                     'FLF_',Path_s020_FouLFM, Path_s040_zrange, Path_s033Lsample];
    end
    for idxta = 1                                                          % Wave propogation                  
        close all;      clc;        disp('Start Calculating CSF...');
        % Wave propogation                                                 
        Flag_breakpoint = 1
        Flag_Startpoint = 129
        Flag_Finalpoint = 1001
                                  
        H46_calcPSF_WFM_FLFM_FineOnly(  Path_s11c_unifor , Path_s31c_unifor , Data_06_CCD_RF   ,Flag_WFMPSFOnly  ,...
                                        P27_NIP_RefAr_Odd, P27_NIP_RefAr_Eve, P47_MLA_NumAdSim , P47_MLA_NumAd_RF,...
                                        Flag_Startpoint  , Flag_Finalpoint  , Object_33_ZdNum  , Object_35_ZCoor ,...
                                        Step_NIP_Finetune, Fl_01_obj, Ma_06_Mic, NA_01_obj, Ind01_obj, lambdaAir ,...
                                        Step_Propergation, NIP_SegSZ, dis_04_em, det_08MLA, dis_05_mc, lambdaLen ,...
                                        Flag_Profilesim  , P41_Fou_MLATra   , P42_Fou_MLAApt                     ,...
                                        Data_02_formDt   , Data_01_formIm   , Data_00_maxval)
        
        H47_calcPSF_WFM_FLFM_Desampling(Path_s11c_unifor , Path_s31c_unifor , Data_05_Refine  ,...
                                        P27_WFM_RefAd_Odd, P27_WFM_RefAd_Eve, P47_MLA_NumAd_RF,...
                                        Object_33_ZdNum  , Object_35_ZCoor  ,                  ...
                                        Data_02_formDt   , Data_01_formIm   ,                  ...
                                        Flag_Simulation  , Flag_WFMPSFOnly  , Flag_breakpoint)
        S65_Imsave_B16_MIP_3D_Col(Image_Path,Image_form,Image_Data,Index_Col,Flag_File)
                                    
    end

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    